# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fc_rank_mat <- function(phi_N_3plusr) {
    .Call(`_PanelQGARCHwithFactor_fc_rank_mat`, phi_N_3plusr)
}

fc_phi_N_homo <- function(theta_vec, g_vec, changepoints_vec, rank_mat) {
    .Call(`_PanelQGARCHwithFactor_fc_phi_N_homo`, theta_vec, g_vec, changepoints_vec, rank_mat)
}

fc_calculate_segment_means <- function(vector_ascend, points) {
    .Call(`_PanelQGARCHwithFactor_fc_calculate_segment_means`, vector_ascend, points)
}

fc_theta_initial_IN_optim <- function(phiini_N_3plusr, g_vec, changepoints_vec) {
    .Call(`_PanelQGARCHwithFactor_fc_theta_initial_IN_optim`, phiini_N_3plusr, g_vec, changepoints_vec)
}

fc_Delta_ijh <- function(i, j, h, vec_ascend) {
    .Call(`_PanelQGARCHwithFactor_fc_Delta_ijh`, i, j, h, vec_ascend)
}

fc_changepoints <- function(delta, i, j, vec_ascend) {
    .Call(`_PanelQGARCHwithFactor_fc_changepoints`, delta, i, j, vec_ascend)
}

fc_g_changepoints_vec <- function(phi_N_3plusr, delta_123r) {
    .Call(`_PanelQGARCHwithFactor_fc_g_changepoints_vec`, phi_N_3plusr, delta_123r)
}

fc_loss_panelQR <- function(tau, phi_N_3plusr, Y_N_T, Factors_r_T, w_N_T) {
    .Call(`_PanelQGARCHwithFactor_fc_loss_panelQR`, tau, phi_N_3plusr, Y_N_T, Factors_r_T, w_N_T)
}

fc3_1_select_delta_tau_BIC <- function(tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat) {
    .Call(`_PanelQGARCHwithFactor_fc3_1_select_delta_tau_BIC`, tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat)
}

fc3_2_select_delta_tau_BIC <- function(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat) {
    .Call(`_PanelQGARCHwithFactor_fc3_2_select_delta_tau_BIC`, if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat)
}

fc_partition_phi_N <- function(g_vec, changepoints_vec, rank_mat) {
    .Call(`_PanelQGARCHwithFactor_fc_partition_phi_N`, g_vec, changepoints_vec, rank_mat)
}

#' Self-weight function based on He & Yi (2021)
#'
#'
#'
#' @param Y Vector. Data.
#' @param C Double. Quantile of Y or |Y|.
#'
#' @export
NULL

fc_weighs_NT <- function(Y_N_T, c_N) {
    .Call(`_PanelQGARCHwithFactor_fc_weighs_NT`, Y_N_T, c_N)
}

fc_phitilde_N_tau <- function(tau, Y_N_T, Factors_r_T, w_N_T) {
    .Call(`_PanelQGARCHwithFactor_fc_phitilde_N_tau`, tau, Y_N_T, Factors_r_T, w_N_T)
}

