// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fc_rank_mat
arma::mat fc_rank_mat(arma::mat phi_N_3plusr);
RcppExport SEXP _PanelQGARCHwithFactor_fc_rank_mat(SEXP phi_N_3plusrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type phi_N_3plusr(phi_N_3plusrSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_rank_mat(phi_N_3plusr));
    return rcpp_result_gen;
END_RCPP
}
// fc_phi_N_homo
arma::mat fc_phi_N_homo(arma::vec theta_vec, arma::vec g_vec, arma::vec changepoints_vec, arma::mat rank_mat);
RcppExport SEXP _PanelQGARCHwithFactor_fc_phi_N_homo(SEXP theta_vecSEXP, SEXP g_vecSEXP, SEXP changepoints_vecSEXP, SEXP rank_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type theta_vec(theta_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type g_vec(g_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type changepoints_vec(changepoints_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rank_mat(rank_matSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_phi_N_homo(theta_vec, g_vec, changepoints_vec, rank_mat));
    return rcpp_result_gen;
END_RCPP
}
// fc_calculate_segment_means
arma::vec fc_calculate_segment_means(arma::vec vector_ascend, arma::vec points);
RcppExport SEXP _PanelQGARCHwithFactor_fc_calculate_segment_means(SEXP vector_ascendSEXP, SEXP pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type vector_ascend(vector_ascendSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type points(pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_calculate_segment_means(vector_ascend, points));
    return rcpp_result_gen;
END_RCPP
}
// fc_theta_initial_IN_optim
arma::vec fc_theta_initial_IN_optim(arma::mat phiini_N_3plusr, arma::vec g_vec, arma::vec changepoints_vec);
RcppExport SEXP _PanelQGARCHwithFactor_fc_theta_initial_IN_optim(SEXP phiini_N_3plusrSEXP, SEXP g_vecSEXP, SEXP changepoints_vecSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type phiini_N_3plusr(phiini_N_3plusrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type g_vec(g_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type changepoints_vec(changepoints_vecSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_theta_initial_IN_optim(phiini_N_3plusr, g_vec, changepoints_vec));
    return rcpp_result_gen;
END_RCPP
}
// fc_Delta_ijh
double fc_Delta_ijh(int i, int j, int h, arma::vec vec_ascend);
RcppExport SEXP _PanelQGARCHwithFactor_fc_Delta_ijh(SEXP iSEXP, SEXP jSEXP, SEXP hSEXP, SEXP vec_ascendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< int >::type h(hSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vec_ascend(vec_ascendSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_Delta_ijh(i, j, h, vec_ascend));
    return rcpp_result_gen;
END_RCPP
}
// fc_changepoints
arma::Col<int> fc_changepoints(double delta, int i, int j, arma::vec vec_ascend);
RcppExport SEXP _PanelQGARCHwithFactor_fc_changepoints(SEXP deltaSEXP, SEXP iSEXP, SEXP jSEXP, SEXP vec_ascendSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type j(jSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type vec_ascend(vec_ascendSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_changepoints(delta, i, j, vec_ascend));
    return rcpp_result_gen;
END_RCPP
}
// fc_g_changepoints_vec
arma::Col<int> fc_g_changepoints_vec(arma::mat phi_N_3plusr, arma::vec delta_123r);
RcppExport SEXP _PanelQGARCHwithFactor_fc_g_changepoints_vec(SEXP phi_N_3plusrSEXP, SEXP delta_123rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type phi_N_3plusr(phi_N_3plusrSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_123r(delta_123rSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_g_changepoints_vec(phi_N_3plusr, delta_123r));
    return rcpp_result_gen;
END_RCPP
}
// fc_loss_panelQR
double fc_loss_panelQR(double tau, arma::mat phi_N_3plusr, arma::mat Y_N_T, arma::mat Factors_r_T, arma::mat w_N_T);
RcppExport SEXP _PanelQGARCHwithFactor_fc_loss_panelQR(SEXP tauSEXP, SEXP phi_N_3plusrSEXP, SEXP Y_N_TSEXP, SEXP Factors_r_TSEXP, SEXP w_N_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phi_N_3plusr(phi_N_3plusrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y_N_T(Y_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Factors_r_T(Factors_r_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w_N_T(w_N_TSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_loss_panelQR(tau, phi_N_3plusr, Y_N_T, Factors_r_T, w_N_T));
    return rcpp_result_gen;
END_RCPP
}
// fc3_1_select_delta_tau_BIC
arma::vec fc3_1_select_delta_tau_BIC(double tolerance, int num_candid_onesplit, arma::vec delta_123r_candid_lower, arma::vec delta_123r_candid_upper, double tau, arma::mat Y_N_T, arma::mat Factors_r_T, arma::mat w_N_T, arma::mat phitilde_N_3plusr, arma::mat rank_mat);
RcppExport SEXP _PanelQGARCHwithFactor_fc3_1_select_delta_tau_BIC(SEXP toleranceSEXP, SEXP num_candid_onesplitSEXP, SEXP delta_123r_candid_lowerSEXP, SEXP delta_123r_candid_upperSEXP, SEXP tauSEXP, SEXP Y_N_TSEXP, SEXP Factors_r_TSEXP, SEXP w_N_TSEXP, SEXP phitilde_N_3plusrSEXP, SEXP rank_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type num_candid_onesplit(num_candid_onesplitSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_123r_candid_lower(delta_123r_candid_lowerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_123r_candid_upper(delta_123r_candid_upperSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y_N_T(Y_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Factors_r_T(Factors_r_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w_N_T(w_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phitilde_N_3plusr(phitilde_N_3plusrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rank_mat(rank_matSEXP);
    rcpp_result_gen = Rcpp::wrap(fc3_1_select_delta_tau_BIC(tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat));
    return rcpp_result_gen;
END_RCPP
}
// fc3_2_select_delta_tau_BIC
arma::vec fc3_2_select_delta_tau_BIC(arma::Col<int> if_group_numeric, int if_mean_numeric, double tolerance, int num_candid_onesplit, arma::vec delta_123r_candid_lower, arma::vec delta_123r_candid_upper, double tau, arma::mat Y_N_T, arma::mat Factors_r_T, arma::mat w_N_T, arma::mat phitilde_N_3plusr, arma::mat rank_mat);
RcppExport SEXP _PanelQGARCHwithFactor_fc3_2_select_delta_tau_BIC(SEXP if_group_numericSEXP, SEXP if_mean_numericSEXP, SEXP toleranceSEXP, SEXP num_candid_onesplitSEXP, SEXP delta_123r_candid_lowerSEXP, SEXP delta_123r_candid_upperSEXP, SEXP tauSEXP, SEXP Y_N_TSEXP, SEXP Factors_r_TSEXP, SEXP w_N_TSEXP, SEXP phitilde_N_3plusrSEXP, SEXP rank_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::Col<int> >::type if_group_numeric(if_group_numericSEXP);
    Rcpp::traits::input_parameter< int >::type if_mean_numeric(if_mean_numericSEXP);
    Rcpp::traits::input_parameter< double >::type tolerance(toleranceSEXP);
    Rcpp::traits::input_parameter< int >::type num_candid_onesplit(num_candid_onesplitSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_123r_candid_lower(delta_123r_candid_lowerSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type delta_123r_candid_upper(delta_123r_candid_upperSEXP);
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y_N_T(Y_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Factors_r_T(Factors_r_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w_N_T(w_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type phitilde_N_3plusr(phitilde_N_3plusrSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rank_mat(rank_matSEXP);
    rcpp_result_gen = Rcpp::wrap(fc3_2_select_delta_tau_BIC(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123r_candid_lower, delta_123r_candid_upper, tau, Y_N_T, Factors_r_T, w_N_T, phitilde_N_3plusr, rank_mat));
    return rcpp_result_gen;
END_RCPP
}
// fc_partition_phi_N
arma::mat fc_partition_phi_N(arma::vec g_vec, arma::vec changepoints_vec, arma::mat rank_mat);
RcppExport SEXP _PanelQGARCHwithFactor_fc_partition_phi_N(SEXP g_vecSEXP, SEXP changepoints_vecSEXP, SEXP rank_matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type g_vec(g_vecSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type changepoints_vec(changepoints_vecSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rank_mat(rank_matSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_partition_phi_N(g_vec, changepoints_vec, rank_mat));
    return rcpp_result_gen;
END_RCPP
}
// fc_weighs_NT
arma::mat fc_weighs_NT(arma::mat Y_N_T, arma::vec c_N);
RcppExport SEXP _PanelQGARCHwithFactor_fc_weighs_NT(SEXP Y_N_TSEXP, SEXP c_NSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type Y_N_T(Y_N_TSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type c_N(c_NSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_weighs_NT(Y_N_T, c_N));
    return rcpp_result_gen;
END_RCPP
}
// fc_phitilde_N_tau
arma::mat fc_phitilde_N_tau(double tau, arma::mat Y_N_T, arma::mat Factors_r_T, arma::mat w_N_T);
RcppExport SEXP _PanelQGARCHwithFactor_fc_phitilde_N_tau(SEXP tauSEXP, SEXP Y_N_TSEXP, SEXP Factors_r_TSEXP, SEXP w_N_TSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type tau(tauSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Y_N_T(Y_N_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Factors_r_T(Factors_r_TSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type w_N_T(w_N_TSEXP);
    rcpp_result_gen = Rcpp::wrap(fc_phitilde_N_tau(tau, Y_N_T, Factors_r_T, w_N_T));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PanelQGARCHwithFactor_fc_rank_mat", (DL_FUNC) &_PanelQGARCHwithFactor_fc_rank_mat, 1},
    {"_PanelQGARCHwithFactor_fc_phi_N_homo", (DL_FUNC) &_PanelQGARCHwithFactor_fc_phi_N_homo, 4},
    {"_PanelQGARCHwithFactor_fc_calculate_segment_means", (DL_FUNC) &_PanelQGARCHwithFactor_fc_calculate_segment_means, 2},
    {"_PanelQGARCHwithFactor_fc_theta_initial_IN_optim", (DL_FUNC) &_PanelQGARCHwithFactor_fc_theta_initial_IN_optim, 3},
    {"_PanelQGARCHwithFactor_fc_Delta_ijh", (DL_FUNC) &_PanelQGARCHwithFactor_fc_Delta_ijh, 4},
    {"_PanelQGARCHwithFactor_fc_changepoints", (DL_FUNC) &_PanelQGARCHwithFactor_fc_changepoints, 4},
    {"_PanelQGARCHwithFactor_fc_g_changepoints_vec", (DL_FUNC) &_PanelQGARCHwithFactor_fc_g_changepoints_vec, 2},
    {"_PanelQGARCHwithFactor_fc_loss_panelQR", (DL_FUNC) &_PanelQGARCHwithFactor_fc_loss_panelQR, 5},
    {"_PanelQGARCHwithFactor_fc3_1_select_delta_tau_BIC", (DL_FUNC) &_PanelQGARCHwithFactor_fc3_1_select_delta_tau_BIC, 10},
    {"_PanelQGARCHwithFactor_fc3_2_select_delta_tau_BIC", (DL_FUNC) &_PanelQGARCHwithFactor_fc3_2_select_delta_tau_BIC, 12},
    {"_PanelQGARCHwithFactor_fc_partition_phi_N", (DL_FUNC) &_PanelQGARCHwithFactor_fc_partition_phi_N, 3},
    {"_PanelQGARCHwithFactor_fc_weighs_NT", (DL_FUNC) &_PanelQGARCHwithFactor_fc_weighs_NT, 2},
    {"_PanelQGARCHwithFactor_fc_phitilde_N_tau", (DL_FUNC) &_PanelQGARCHwithFactor_fc_phitilde_N_tau, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_PanelQGARCHwithFactor(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
