# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fc_Delta_ijh <- function(i, j, h, vec_ascend) {
    .Call(`_PanelQGARCH_fc_Delta_ijh`, i, j, h, vec_ascend)
}

fc_changepoints <- function(delta, i, j, vec_ascend) {
    .Call(`_PanelQGARCH_fc_changepoints`, delta, i, j, vec_ascend)
}

fc_loss_panelQR <- function(tau, phi_N_3, Y_N_T, w_N_T) {
    .Call(`_PanelQGARCH_fc_loss_panelQR`, tau, phi_N_3, Y_N_T, w_N_T)
}

fc_select_delta_tau_BIC <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc_select_delta_tau_BIC`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc_select_delta_tau_CV <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train) {
    .Call(`_PanelQGARCH_fc_select_delta_tau_CV`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train)
}

fc1_1_select_delta_tau_BIC <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc1_1_select_delta_tau_BIC`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc1_2_select_delta_tau_BIC <- function(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc1_2_select_delta_tau_BIC`, if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc2_1_select_delta_tau_BIC <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc2_1_select_delta_tau_BIC`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc2_2_select_delta_tau_BIC <- function(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc2_2_select_delta_tau_BIC`, if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc3_1_select_delta_tau_BIC <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc3_1_select_delta_tau_BIC`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc3_2_select_delta_tau_BIC <- function(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3) {
    .Call(`_PanelQGARCH_fc3_2_select_delta_tau_BIC`, if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, w_N_T, phitilde_N_3)
}

fc_1_select_delta_tau_CV <- function(tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train) {
    .Call(`_PanelQGARCH_fc_1_select_delta_tau_CV`, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train)
}

fc_2_select_delta_tau_CV <- function(if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train) {
    .Call(`_PanelQGARCH_fc_2_select_delta_tau_CV`, if_group_numeric, if_mean_numeric, tolerance, num_candid_onesplit, delta_123_candid_lower, delta_123_candid_upper, tau, Y_N_T, testLength, w_N_T_train, phitilde_N_3_train)
}

#' Self-weight function based on He & Yi (2021)
#'
#'
#'
#' @param Y Vector. Data.
#' @param C Double. Quantile of Y or |Y|.
#'
#' @export
NULL

fc_weighs_NT <- function(Y_N_T, c_N) {
    .Call(`_PanelQGARCH_fc_weighs_NT`, Y_N_T, c_N)
}

fc_phitilde_N_tau <- function(tau, Y_N_T, w_N_T) {
    .Call(`_PanelQGARCH_fc_phitilde_N_tau`, tau, Y_N_T, w_N_T)
}

fc_q_y_t0plus1 <- function(Y_N_t0, phihat_N_3) {
    .Call(`_PanelQGARCH_fc_q_y_t0plus1`, Y_N_t0, phihat_N_3)
}

fc_ifCovers_vec <- function(observations_vec, q_vec) {
    .Call(`_PanelQGARCH_fc_ifCovers_vec`, observations_vec, q_vec)
}

